#!/bin/bash

##
##  Automate configuration script.
##  
##  Author: Kim Leo <kenpusney@gmail.com>
##  http://github.com/kenpusney
##

##
## eval_rec : Evaluate the script files in `dir` recursively.
## @usage : eval_rec <dir>
##
eval_rec() {
    cd $1
    for file in `ls`
    do
        [ -d $file ] && eval_rec $file
        [ -f $file ] && eval_script $file
    done
    cd ..
}

eval_script() {
    #By `file` command detected type.
    case `file $1` in
        *"shell script"* ) source $1 ;;
        *"perl script"* ) perl $1 ;;
        *"awk script"* ) awk -f $1 ;;
        *"python script"* ) python $1 ;;
        * )
        #By file extension.
            case $1 in
                *.sh ) bash $1 ;;
                *.pl ) perl $1 ;;
                *.py ) python $1 ;;
                * ) 
                    case `head -1 $1` in
                        *"bash" ) bash $1 ;;
                        *"sh"  ) sh $1 ;;
                        *"perl" ) perl $1 ;;
                        *"python") python $1 ;;
                    esac ;;
            esac ;;
    esac
    
}

konf_exec() {
    for file in $@
    do
        if [ -f $file ]
        then
            eval_script $file
        elif [ -f "scripts/$file" ]
        then 
            eval_script "scripts/$file"
        else
            echo "[Error]Unknow Scripts: $file."
            exit 1
        fi
    done
}

case $1 in
    ## Evaluations:
    "exec" ) 
        shift
        [ $# -eq 0 ] && eval_rec scripts 
        [ $# -gt 0 ] && case $1 in 
                all ) eval_rec scripts ;;
                * ) konf_exec $@ ;;
            esac ;;
    ## Cover Configuration files.
    "conf" ) 
        shift
        cd ./conf/
        
        ;;
    ## Backup Configuration files.
    "backup" )  ;;
        cd ./conf/
    * ) echo "[Errror]Unknown command." 
        exit 1 ;;
esac





